DROP TABLE IF EXISTS `data`;
CREATE TABLE IF NOT EXISTS `data` (
    `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `fall` INT UNSIGNED,
    `gps` TEXT
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;