DROP TABLE IF EXISTS `device`;
CREATE TABLE IF NOT EXISTS `device` (
    `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `alive` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `light` INT UNSIGNED DEFAULT 0,
    `sound` INT UNSIGNED DEFAULT 0,
    `fall` INT UNSIGNED,
    `gps` TEXT
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;